/**
 * Tenant-scoped access to the analytics-pipeline models.
 *
 * `withTenant(tenantId, fn)` is the ONLY supported way for application code
 * to read or write analytics.event / analytics.outbox / analytics.tenant_config.
 * Direct prisma.analyticsPipelineEvent.* access is blocked at runtime in dev
 * by the guard wired into app/_lib/db/prisma.ts.
 *
 * The scoped client returned to `fn` auto-injects `tenantId` (the Prisma
 * TS-side field name; mapped to the `tenant_id` column at the SQL boundary
 * by `@map`) on every operation, and rejects any caller-supplied `tenantId`
 * that doesn't match the scope. There is no path for analytics code to read
 * or mutate another tenant's rows by accident.
 *
 * ── Operation surface table ────────────────────────────────────────────────
 *
 * Prisma 6 exposes 17 model operations. `$allOperations` intercepts every
 * one. For each, this is what the scoped client does:
 *
 *   READ — inject tenantId into `where`, reject mismatch:
 *     findUnique, findUniqueOrThrow, findFirst, findFirstOrThrow,
 *     findMany, count, aggregate, groupBy
 *
 *   WRITE-CREATE — inject tenantId into `data`, reject mismatch:
 *     create, createMany, createManyAndReturn
 *
 *   WRITE-MUTATE — inject into `where`, validate `data` does not flip
 *   tenantId, reject mismatch:
 *     update, updateMany, updateManyAndReturn, delete, deleteMany
 *
 *   WRITE-UPSERT — inject into `where`, inject into `create`, validate
 *   `update` does not flip tenantId, reject mismatch:
 *     upsert
 *
 * tenantId is immutable on existing rows by convention enforced here. The
 * helper never injects tenantId into update / upsert.update payloads — only
 * into create paths and where filters. A caller that puts `tenantId` in
 * update.data with a value matching the scope is allowed (no-op); a
 * mismatched value throws.
 *
 * Phase 1+ relies on this contract. Don't change it without updating Phase 1
 * callers and the verification suite together.
 */

import type { PrismaClient } from "@prisma/client";
import {
  _unguardedAnalyticsPipelineClient,
} from "@/app/_lib/db/prisma";

// ── Tenant identifier validation ─────────────────────────────────────────
//
// Tenant.id is generated by Prisma's `cuid()` default in prisma/schema.prisma,
// which is cuid v1: a 25-char string starting with "c", followed by 24
// lowercase alphanumerics. Examples: cl9ebqhxk00003b6082g4lf6r.
//
// We do NOT accept Clerk Org IDs (org_*) here. The pipeline's tenant_id is
// the internal Tenant.id, matching the convention used by every other
// tenant-scoped table in the codebase.
const TENANT_ID_REGEX = /^c[a-z0-9]{24}$/;

// ── Errors ───────────────────────────────────────────────────────────────

export class AnalyticsTenantError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "AnalyticsTenantError";
  }
}

export class AnalyticsTenantMissingError extends AnalyticsTenantError {
  constructor() {
    super(
      "withTenant: tenantId is required but was empty, null, or undefined.",
    );
    this.name = "AnalyticsTenantMissingError";
  }
}

export class AnalyticsTenantInvalidError extends AnalyticsTenantError {
  constructor(tenantId: string) {
    super(
      `withTenant: tenantId ${JSON.stringify(
        tenantId,
      )} does not match Tenant.id format (cuid v1: /^c[a-z0-9]{24}$/).`,
    );
    this.name = "AnalyticsTenantInvalidError";
  }
}

export class AnalyticsTenantMismatchError extends AnalyticsTenantError {
  constructor(
    model: string,
    operation: string,
    scopeTenantId: string,
    attemptedTenantId: unknown,
  ) {
    super(
      `withTenant: ${model}.${operation} was called with tenant_id=${JSON.stringify(
        attemptedTenantId,
      )} inside a scope bound to tenant_id=${JSON.stringify(scopeTenantId)}. ` +
        "Tenant scopes are immutable — open a new withTenant() block for the other tenant.",
    );
    this.name = "AnalyticsTenantMismatchError";
  }
}

// ── Branded type for the scoped client ───────────────────────────────────
//
// The brand prevents callers from accidentally typing the global `prisma`
// export as an AnalyticsPipelineScope or vice-versa. They are not
// interchangeable: the scoped client auto-injects tenantId; the global
// client doesn't.
//
// We define the type as an explicit object of per-model picks rather than
// `ReturnType<typeof buildScopedClient>` (i.e. the result of `$extends(...)`).
// Letting TS expand the `$extends` return type forces it to materialize Prisma's
// full DynamicClientExtensionThis<...> generic — recursive across all 144 models
// — at every call site that imports this type. That's what blew the Vercel build
// to 11.5 GB during `tsc --noEmit`. The explicit picks below give callers the
// same useful surface (the three pipeline models) at a flat, predictable cost.
//
// The runtime value still comes from `_unguardedAnalyticsPipelineClient.$extends(...)`;
// only the exported *type* changes. `withTenant` casts the runtime client to
// `AnalyticsPipelineScope` at its return boundary.

// Operations whose `where` clause is optional (Prisma allows omitting it
// entirely). For these, when the caller doesn't pass a where, we inject one
// containing only tenant_id so the operation stays scoped.
const NO_WHERE_OK = new Set([
  "findMany",
  "count",
  "aggregate",
  "groupBy",
  "deleteMany",
  "updateMany",
  "updateManyAndReturn",
]);

const CREATE_OPS = new Set([
  "create",
  "createMany",
  "createManyAndReturn",
]);

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return (
    value !== null &&
    typeof value === "object" &&
    !Array.isArray(value)
  );
}

function injectIntoCreateData(
  scopeTenantId: string,
  model: string,
  operation: string,
  data: unknown,
): unknown {
  if (Array.isArray(data)) {
    return data.map((row) => {
      if (!isPlainObject(row)) return row;
      if ("tenantId" in row) {
        if (row.tenantId !== scopeTenantId) {
          throw new AnalyticsTenantMismatchError(
            model,
            operation,
            scopeTenantId,
            row.tenantId,
          );
        }
        return row;
      }
      return { ...row, tenantId: scopeTenantId };
    });
  }
  if (isPlainObject(data)) {
    if ("tenantId" in data) {
      if (data.tenantId !== scopeTenantId) {
        throw new AnalyticsTenantMismatchError(
          model,
          operation,
          scopeTenantId,
          data.tenantId,
        );
      }
      return data;
    }
    return { ...data, tenantId: scopeTenantId };
  }
  return data;
}

function validateMutateData(
  scopeTenantId: string,
  model: string,
  operation: string,
  data: unknown,
): void {
  // For update / upsert.update we never inject tenant_id (it's immutable on
  // existing rows by convention). But if the caller puts tenant_id into the
  // payload, it must match the scope or we throw — the scope is the source
  // of truth.
  if (!isPlainObject(data)) return;
  if ("tenantId" in data && data.tenantId !== scopeTenantId) {
    throw new AnalyticsTenantMismatchError(
      model,
      operation,
      scopeTenantId,
      data.tenantId,
    );
  }
}

function injectIntoWhere(
  scopeTenantId: string,
  model: string,
  operation: string,
  args: Record<string, unknown> | undefined,
): void {
  if (!args) return;
  const where = args.where;
  if (isPlainObject(where)) {
    if ("tenantId" in where) {
      if (where.tenantId !== scopeTenantId) {
        throw new AnalyticsTenantMismatchError(
          model,
          operation,
          scopeTenantId,
          where.tenantId,
        );
      }
      return;
    }
    args.where = { ...where, tenantId: scopeTenantId };
    return;
  }
  // No where (or null/undefined). Only inject one if the operation allows it.
  if (NO_WHERE_OK.has(operation)) {
    args.where = { tenantId: scopeTenantId };
  }
  // Else: leave args.where alone. Prisma will error with its own message
  // (e.g. findUnique requires a unique-where) — preferable to us injecting
  // a non-unique field and triggering a confusing Prisma input-validation
  // error.
}

/**
 * Pure args-rewriter applied by `$allOperations`. Extracted for unit tests so
 * the operation matrix can be covered without a real Prisma client.
 *
 * Throws AnalyticsTenantMismatchError when the caller-provided args contain a
 * tenantId that disagrees with the scope. Returns the rewritten args (a
 * shallow clone of the input, so callers' originals are untouched).
 */
export function _applyTenantScopeForTests(
  scopeTenantId: string,
  model: string,
  operation: string,
  args: unknown,
): Record<string, unknown> {
  const next: Record<string, unknown> = isPlainObject(args)
    ? { ...args }
    : ({} as Record<string, unknown>);

  // 1. Where-side injection / validation
  injectIntoWhere(scopeTenantId, model, operation, next);

  // 2. Data-side injection / validation
  if (CREATE_OPS.has(operation) && "data" in next) {
    next.data = injectIntoCreateData(
      scopeTenantId,
      model,
      operation,
      next.data,
    );
  } else if (
    (operation === "update" ||
      operation === "updateMany" ||
      operation === "updateManyAndReturn") &&
    "data" in next
  ) {
    validateMutateData(scopeTenantId, model, operation, next.data);
  }

  // 3. Upsert: where (handled above) + create + update
  if (operation === "upsert") {
    if ("create" in next) {
      next.create = injectIntoCreateData(
        scopeTenantId,
        model,
        "upsert.create",
        next.create,
      );
    }
    if ("update" in next) {
      validateMutateData(scopeTenantId, model, "upsert.update", next.update);
    }
  }

  return next;
}

function buildScopedClient(scopeTenantId: string) {
  const guard = {
    async $allOperations(params: {
      model: string;
      operation: string;
      args: unknown;
      query: (args: unknown) => Promise<unknown>;
    }) {
      const { model, operation, args, query } = params;
      const next = _applyTenantScopeForTests(
        scopeTenantId,
        model,
        operation,
        args,
      );
      return query(next);
    },
  };

  return _unguardedAnalyticsPipelineClient.$extends({
    name: "analytics-pipeline-tenant-scope",
    query: {
      analyticsPipelineEvent: guard,
      analyticsPipelineOutbox: guard,
      analyticsPipelineTenantConfig: guard,
    },
  });
}

export type AnalyticsPipelineScope = {
  analyticsPipelineEvent: PrismaClient["analyticsPipelineEvent"];
  analyticsPipelineOutbox: PrismaClient["analyticsPipelineOutbox"];
  analyticsPipelineTenantConfig: PrismaClient["analyticsPipelineTenantConfig"];
} & { readonly __analyticsPipelineScopeBrand: unique symbol };

/**
 * Run `fn` against a tenant-scoped analytics-pipeline client.
 *
 * The scoped client auto-injects `tenant_id` on every operation across the
 * three pipeline models. Caller-provided `tenant_id` values that don't match
 * `tenantId` raise `AnalyticsTenantMismatchError`. Empty / invalid `tenantId`
 * raises `AnalyticsTenantMissingError` / `AnalyticsTenantInvalidError`.
 *
 * The scope ends when `fn` resolves (or rejects). Don't return the `db`
 * argument — it's branded specifically to flag that mistake at compile time.
 */
export async function withTenant<T>(
  tenantId: string | null | undefined,
  fn: (db: AnalyticsPipelineScope) => Promise<T>,
): Promise<T> {
  if (tenantId === null || tenantId === undefined || tenantId === "") {
    throw new AnalyticsTenantMissingError();
  }
  if (!TENANT_ID_REGEX.test(tenantId)) {
    throw new AnalyticsTenantInvalidError(tenantId);
  }
  const scoped = buildScopedClient(tenantId) as unknown as AnalyticsPipelineScope;
  return fn(scoped);
}
