/**
 * cart_started v0.2.0 (storefront)
 * ────────────────────────────────
 *
 * Fires when the FIRST item is added to a previously-empty cart. Pairs
 * with `cart_updated` (subsequent mutations), `cart_abandoned` (guest
 * left with non-empty cart), and `checkout_started` (cart pushed to
 * checkout) for funnel analysis.
 *
 * Version history:
 *   v0.1.0  Required `accommodation_id`. Deprecated — the actual cart
 *           in the codebase is a Shop product cart, not an
 *           accommodation cart. Preserved at
 *           `legacy/cart-started-v0.1.0.ts` for outbox-drain
 *           backward-compat only.
 *   v0.2.0  Replaces `accommodation_id` with `product_id` (Product.id
 *           cuid). Documents the full `cart_id` lifecycle. Current.
 *
 * Triggered by: the analytics worker (Phase 3 PR-B), subscribed to
 * cart-state changes via the cart context. Worker fires only when
 * `cart.items.length === 0` immediately before the add.
 *
 * Consent category: `analytics`.
 *
 * ──────────────────────────────────────────────────────────────────────
 * Semantic Contract
 * ──────────────────────────────────────────────────────────────────────
 *
 * `cart_id`. ULID generated by the cart client when the cart hydrates
 *   from a previously-empty state. Storage: `localStorage` alongside
 *   the cart state (`bf_cart_{tenantId}`). Lifecycle:
 *
 *     • The same `cart_id` is preserved while the cart contains ≥1
 *       item, including across browser sessions (close + reopen with
 *       cart still in localStorage → SAME cart_id).
 *     • Regenerated on `clearCart()` — both manual empty AND the
 *       auto-clear that fires on the `payment_succeeded` confirmation
 *       page. The next add-to-empty produces a new id.
 *     • Multi-tab: shared via localStorage. All tabs see the SAME
 *       cart_id. `cart_started` fires only ONCE per cart_id — the
 *       first tab to add the first item emits; other tabs that
 *       hydrate an already-populated cart do NOT re-emit
 *       cart_started.
 *     • NOT correlated with `session_id` (which is sessionStorage,
 *       per-tab, and rotates on idle). A cart can outlive a session;
 *       a session can exist without a cart.
 *
 * `product_id`. The `Product.id` value (cuid) of the first item added
 *   to the previously-empty cart. NOT a slug, NOT a `variantId`. For
 *   carts whose first item is a Product variant, the parent
 *   `Product.id` is emitted — variant identity is not tracked at
 *   `cart_started` level. Phase 5 readers that need variant detail
 *   consult subsequent `cart_updated` events.
 *
 * `cart_total`. Object `{ amount, currency }`. Per the global
 *   convention in `base.ts`: `amount` is an integer in MINOR UNITS of
 *   the named currency (ören for SEK, cents for EUR). `currency` is
 *   an ISO 4217 three-letter UPPERCASE code. The total is the cart's
 *   running total AFTER the first item is added (i.e. the value of
 *   the just-added item if it's the only item, or the sum if a
 *   single addToCart call adds multiple line items).
 *
 * `storefront_context`. Shared StorefrontContextSchema fields. See
 *   `_storefront-context.ts` for the contract on each.
 */

import { z } from "zod";

import { BaseEventSchema } from "./base";
import { StorefrontContextSchema } from "./_storefront-context";

export const CartStartedPayloadSchema = StorefrontContextSchema.and(
  z.object({
    cart_id: z.string().min(1),
    product_id: z.string().min(1),
    cart_total: z.object({
      amount: z.number().int().nonnegative(),
      currency: z.string().length(3),
    }),
  }),
);

export const CartStartedSchema = BaseEventSchema.and(
  z.object({
    event_name: z.literal("cart_started"),
    schema_version: z.literal("0.2.0"),
    payload: CartStartedPayloadSchema,
  }),
);

export type CartStartedPayload = z.infer<typeof CartStartedPayloadSchema>;
export type CartStartedEvent = z.infer<typeof CartStartedSchema>;
