/**
 * Customer-facing invoice payment page.
 *
 * URL: {portalSlug}.rutgr.com/invoice/{shareLinkToken}
 *
 * Generated by `sendInvoice` (admin/_lib/draft-orders/lifecycle.ts) and
 * delivered to the buyer via the draft-invoice email template. Renders
 * line items + totals on the server, then mounts <InvoiceClient /> for
 * the embedded Stripe Elements UI.
 *
 * Branching:
 *   - tenant unresolved        → notFound()
 *   - draft not found          → notFound()
 *   - shareLinkExpiresAt < now → ExpiredView
 *   - status PAID | COMPLETED  → PaidView
 *   - status INVOICED | OVERDUE → InvoiceClient
 */

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { resolveTenantFromHost } from "@/app/(guest)/_lib/tenant/resolveTenantFromHost";
import { getDraftByShareToken } from "@/app/_lib/draft-orders";
import { formatSek } from "@/app/_lib/money/format";
import { InvoiceClient } from "./InvoiceClient";
import "../invoice.css";

export const dynamic = "force-dynamic";
// Per recon Q6 (LOCKED): never index PII-bearing pages.
export const metadata: Metadata = {
  robots: { index: false, follow: false },
};

type PageProps = {
  params: Promise<{ token: string }>;
};

export default async function InvoicePage({ params }: PageProps) {
  const { token } = await params;

  const tenant = await resolveTenantFromHost();
  if (!tenant) notFound();

  const result = await getDraftByShareToken(token, tenant.id);
  if (!result) notFound();

  const { draft, expired } = result;

  if (expired) {
    return <ExpiredView displayNumber={draft.displayNumber} />;
  }

  if (draft.status === "PAID" || draft.status === "COMPLETED") {
    return (
      <PaidView
        displayNumber={draft.displayNumber}
        totalCents={draft.totalCents}
        currency={draft.currency}
      />
    );
  }

  // INVOICED | OVERDUE — mount the payment UI.
  return (
    <main className="inv">
      <header className="inv__header">
        <h1 className="inv__title">Faktura {draft.displayNumber}</h1>
        {draft.invoiceSentAt !== null ? (
          <p className="inv__sent">
            Skickad {formatDate(draft.invoiceSentAt)}
          </p>
        ) : null}
      </header>

      <section className="inv__summary" aria-label="Beställningssammanfattning">
        <ul className="inv__lines">
          {draft.lineItems.map((line) => (
            <li key={line.id} className="inv__line">
              <div className="inv__line-main">
                <span className="inv__line-title">{line.title}</span>
                {line.variantTitle !== null ? (
                  <span className="inv__line-variant">{line.variantTitle}</span>
                ) : null}
                {line.checkInDate !== null && line.checkOutDate !== null ? (
                  <span className="inv__line-meta">
                    {formatDateRange(line.checkInDate, line.checkOutDate)}
                    {line.nights !== null
                      ? ` · ${line.nights} nätter`
                      : null}
                  </span>
                ) : null}
                {line.quantity > 1 ? (
                  <span className="inv__line-qty">Antal: {line.quantity}</span>
                ) : null}
              </div>
              <span className="inv__line-amount">
                {formatSek(line.totalCents, { currency: draft.currency })}
              </span>
            </li>
          ))}
        </ul>

        <dl className="inv__totals">
          <div className="inv__total-row">
            <dt>Delsumma</dt>
            <dd>
              {formatSek(draft.subtotalCents, { currency: draft.currency })}
            </dd>
          </div>
          {draft.orderDiscountCents > BigInt(0) ? (
            <div className="inv__total-row">
              <dt>
                Rabatt
                {draft.appliedDiscountCode !== null ? (
                  <span className="inv__discount-code">
                    {" "}
                    ({draft.appliedDiscountCode})
                  </span>
                ) : null}
              </dt>
              <dd>
                −
                {formatSek(draft.orderDiscountCents, {
                  currency: draft.currency,
                })}
              </dd>
            </div>
          ) : null}
          {draft.totalTaxCents > BigInt(0) ? (
            <div className="inv__total-row">
              <dt>Moms{draft.taxesIncluded ? " (ingår)" : ""}</dt>
              <dd>
                {formatSek(draft.totalTaxCents, { currency: draft.currency })}
              </dd>
            </div>
          ) : null}
          <div className="inv__total-row inv__total-row--grand">
            <dt>Totalt att betala</dt>
            <dd>
              {formatSek(draft.totalCents, { currency: draft.currency })}
            </dd>
          </div>
        </dl>

        {draft.customerNote !== null && draft.customerNote.length > 0 ? (
          <div className="inv__note">
            <h2 className="inv__note-title">Meddelande från säljaren</h2>
            <p>{draft.customerNote}</p>
          </div>
        ) : null}
      </section>

      <InvoiceClient
        token={token}
        displayNumber={draft.displayNumber}
        totalCents={draft.totalCents.toString()}
        currency={draft.currency}
      />
    </main>
  );
}

// ── Sub-views ───────────────────────────────────────────────────

function ExpiredView({ displayNumber }: { displayNumber: string }) {
  return (
    <main className="inv inv--expired">
      <header className="inv__header">
        <h1 className="inv__title">Faktura {displayNumber}</h1>
      </header>
      <div className="inv__notice">
        <p className="inv__notice-title">Länken har gått ut</p>
        <p className="inv__notice-body">
          Den här faktura-länken är inte längre giltig. Kontakta säljaren
          för att begära en ny.
        </p>
      </div>
    </main>
  );
}

function PaidView({
  displayNumber,
  totalCents,
  currency,
}: {
  displayNumber: string;
  totalCents: bigint;
  currency: string;
}) {
  return (
    <main className="inv inv--paid">
      <header className="inv__header">
        <h1 className="inv__title">Faktura {displayNumber}</h1>
      </header>
      <div className="inv__notice inv__notice--success">
        <p className="inv__notice-title">Tack — fakturan är betald</p>
        <p className="inv__notice-body">
          Vi har mottagit {formatSek(totalCents, { currency })}. En
          bekräftelse skickas till din e-post.
        </p>
      </div>
    </main>
  );
}

// ── Date formatting ─────────────────────────────────────────────

function formatDate(d: Date): string {
  return new Intl.DateTimeFormat("sv-SE", {
    year: "numeric",
    month: "long",
    day: "numeric",
  }).format(d);
}

function formatDateRange(checkInISO: string, checkOutISO: string): string {
  const checkIn = new Date(checkInISO);
  const checkOut = new Date(checkOutISO);
  const fmt = new Intl.DateTimeFormat("sv-SE", {
    month: "short",
    day: "numeric",
  });
  return `${fmt.format(checkIn)} – ${fmt.format(checkOut)}`;
}
