/**
 * Country dial codes for phone input.
 * Names are in each country's native language.
 * Sorted alphabetically by native name.
 * Country codes are ISO 3166-1 alpha-2 (lowercase).
 */

export type Country = {
  code: string;
  name: string;   // Native language name
  dial: string;
};

export const COUNTRIES: Country[] = [
  { code: "af", name: "افغانستان", dial: "+93" },
  { code: "al", name: "Shqipëria", dial: "+355" },
  { code: "dz", name: "الجزائر", dial: "+213" },
  { code: "ad", name: "Andorra", dial: "+376" },
  { code: "ao", name: "Angola", dial: "+244" },
  { code: "ag", name: "Antigua and Barbuda", dial: "+1-268" },
  { code: "ar", name: "Argentina", dial: "+54" },
  { code: "am", name: "Հայաստան", dial: "+374" },
  { code: "au", name: "Australia", dial: "+61" },
  { code: "at", name: "Österreich", dial: "+43" },
  { code: "az", name: "Azərbaycan", dial: "+994" },
  { code: "bs", name: "Bahamas", dial: "+1-242" },
  { code: "bh", name: "البحرين", dial: "+973" },
  { code: "bd", name: "বাংলাদেশ", dial: "+880" },
  { code: "bb", name: "Barbados", dial: "+1-246" },
  { code: "by", name: "Беларусь", dial: "+375" },
  { code: "be", name: "België", dial: "+32" },
  { code: "bz", name: "Belize", dial: "+501" },
  { code: "bj", name: "Bénin", dial: "+229" },
  { code: "bt", name: "འབྲུག", dial: "+975" },
  { code: "bo", name: "Bolivia", dial: "+591" },
  { code: "ba", name: "Bosna i Hercegovina", dial: "+387" },
  { code: "bw", name: "Botswana", dial: "+267" },
  { code: "br", name: "Brasil", dial: "+55" },
  { code: "bn", name: "Brunei", dial: "+673" },
  { code: "bg", name: "България", dial: "+359" },
  { code: "bf", name: "Burkina Faso", dial: "+226" },
  { code: "bi", name: "Burundi", dial: "+257" },
  { code: "kh", name: "កម្ពុជា", dial: "+855" },
  { code: "cm", name: "Cameroun", dial: "+237" },
  { code: "ca", name: "Canada", dial: "+1" },
  { code: "cv", name: "Cabo Verde", dial: "+238" },
  { code: "td", name: "Tchad", dial: "+235" },
  { code: "cl", name: "Chile", dial: "+56" },
  { code: "cn", name: "中国", dial: "+86" },
  { code: "co", name: "Colombia", dial: "+57" },
  { code: "km", name: "Komori", dial: "+269" },
  { code: "cg", name: "Congo", dial: "+242" },
  { code: "cd", name: "Congo (RDC)", dial: "+243" },
  { code: "cr", name: "Costa Rica", dial: "+506" },
  { code: "ci", name: "Côte d'Ivoire", dial: "+225" },
  { code: "hr", name: "Hrvatska", dial: "+385" },
  { code: "cu", name: "Cuba", dial: "+53" },
  { code: "cy", name: "Κύπρος", dial: "+357" },
  { code: "cz", name: "Česko", dial: "+420" },
  { code: "dk", name: "Danmark", dial: "+45" },
  { code: "dj", name: "Djibouti", dial: "+253" },
  { code: "dm", name: "Dominica", dial: "+1-767" },
  { code: "do", name: "República Dominicana", dial: "+1-809" },
  { code: "ec", name: "Ecuador", dial: "+593" },
  { code: "eg", name: "مصر", dial: "+20" },
  { code: "sv", name: "El Salvador", dial: "+503" },
  { code: "er", name: "ኤርትራ", dial: "+291" },
  { code: "ee", name: "Eesti", dial: "+372" },
  { code: "sz", name: "Eswatini", dial: "+268" },
  { code: "et", name: "ኢትዮጵያ", dial: "+251" },
  { code: "fj", name: "Fiji", dial: "+679" },
  { code: "fi", name: "Suomi", dial: "+358" },
  { code: "fr", name: "France", dial: "+33" },
  { code: "ga", name: "Gabon", dial: "+241" },
  { code: "gm", name: "Gambia", dial: "+220" },
  { code: "ge", name: "საქართველო", dial: "+995" },
  { code: "de", name: "Deutschland", dial: "+49" },
  { code: "gh", name: "Ghana", dial: "+233" },
  { code: "gr", name: "Ελλάδα", dial: "+30" },
  { code: "gd", name: "Grenada", dial: "+1-473" },
  { code: "gt", name: "Guatemala", dial: "+502" },
  { code: "gn", name: "Guinée", dial: "+224" },
  { code: "gw", name: "Guiné-Bissau", dial: "+245" },
  { code: "gy", name: "Guyana", dial: "+592" },
  { code: "ht", name: "Haïti", dial: "+509" },
  { code: "hn", name: "Honduras", dial: "+504" },
  { code: "hu", name: "Magyarország", dial: "+36" },
  { code: "is", name: "Ísland", dial: "+354" },
  { code: "in", name: "भारत", dial: "+91" },
  { code: "id", name: "Indonesia", dial: "+62" },
  { code: "ir", name: "ایران", dial: "+98" },
  { code: "iq", name: "العراق", dial: "+964" },
  { code: "ie", name: "Ireland", dial: "+353" },
  { code: "il", name: "ישראל", dial: "+972" },
  { code: "it", name: "Italia", dial: "+39" },
  { code: "jm", name: "Jamaica", dial: "+1-876" },
  { code: "jp", name: "日本", dial: "+81" },
  { code: "jo", name: "الأردن", dial: "+962" },
  { code: "kz", name: "Қазақстан", dial: "+7" },
  { code: "ke", name: "Kenya", dial: "+254" },
  { code: "ki", name: "Kiribati", dial: "+686" },
  { code: "kp", name: "조선", dial: "+850" },
  { code: "kr", name: "대한민국", dial: "+82" },
  { code: "kw", name: "الكويت", dial: "+965" },
  { code: "kg", name: "Кыргызстан", dial: "+996" },
  { code: "la", name: "ລາວ", dial: "+856" },
  { code: "lv", name: "Latvija", dial: "+371" },
  { code: "lb", name: "لبنان", dial: "+961" },
  { code: "ls", name: "Lesotho", dial: "+266" },
  { code: "lr", name: "Liberia", dial: "+231" },
  { code: "ly", name: "ليبيا", dial: "+218" },
  { code: "li", name: "Liechtenstein", dial: "+423" },
  { code: "lt", name: "Lietuva", dial: "+370" },
  { code: "lu", name: "Lëtzebuerg", dial: "+352" },
  { code: "mg", name: "Madagasikara", dial: "+261" },
  { code: "mw", name: "Malawi", dial: "+265" },
  { code: "my", name: "Malaysia", dial: "+60" },
  { code: "mv", name: "ދިވެހިރާއްޖެ", dial: "+960" },
  { code: "ml", name: "Mali", dial: "+223" },
  { code: "mt", name: "Malta", dial: "+356" },
  { code: "mr", name: "موريتانيا", dial: "+222" },
  { code: "mu", name: "Mauritius", dial: "+230" },
  { code: "mx", name: "México", dial: "+52" },
  { code: "md", name: "Moldova", dial: "+373" },
  { code: "mc", name: "Monaco", dial: "+377" },
  { code: "mn", name: "Монгол", dial: "+976" },
  { code: "me", name: "Crna Gora", dial: "+382" },
  { code: "ma", name: "المغرب", dial: "+212" },
  { code: "mz", name: "Moçambique", dial: "+258" },
  { code: "mm", name: "မြန်မာ", dial: "+95" },
  { code: "na", name: "Namibia", dial: "+264" },
  { code: "nr", name: "Nauru", dial: "+674" },
  { code: "np", name: "नेपाल", dial: "+977" },
  { code: "nl", name: "Nederland", dial: "+31" },
  { code: "nz", name: "New Zealand", dial: "+64" },
  { code: "ni", name: "Nicaragua", dial: "+505" },
  { code: "ne", name: "Niger", dial: "+227" },
  { code: "ng", name: "Nigeria", dial: "+234" },
  { code: "mk", name: "Северна Македонија", dial: "+389" },
  { code: "no", name: "Norge", dial: "+47" },
  { code: "om", name: "عُمان", dial: "+968" },
  { code: "pk", name: "پاکستان", dial: "+92" },
  { code: "pw", name: "Palau", dial: "+680" },
  { code: "pa", name: "Panamá", dial: "+507" },
  { code: "pg", name: "Papua Niugini", dial: "+675" },
  { code: "py", name: "Paraguay", dial: "+595" },
  { code: "pe", name: "Perú", dial: "+51" },
  { code: "ph", name: "Pilipinas", dial: "+63" },
  { code: "pl", name: "Polska", dial: "+48" },
  { code: "pt", name: "Portugal", dial: "+351" },
  { code: "qa", name: "قطر", dial: "+974" },
  { code: "ro", name: "România", dial: "+40" },
  { code: "ru", name: "Россия", dial: "+7" },
  { code: "rw", name: "Rwanda", dial: "+250" },
  { code: "kn", name: "Saint Kitts and Nevis", dial: "+1-869" },
  { code: "lc", name: "Saint Lucia", dial: "+1-758" },
  { code: "vc", name: "Saint Vincent and the Grenadines", dial: "+1-784" },
  { code: "ws", name: "Sāmoa", dial: "+685" },
  { code: "sm", name: "San Marino", dial: "+378" },
  { code: "st", name: "São Tomé e Príncipe", dial: "+239" },
  { code: "sa", name: "السعودية", dial: "+966" },
  { code: "sn", name: "Sénégal", dial: "+221" },
  { code: "rs", name: "Србија", dial: "+381" },
  { code: "sc", name: "Seychelles", dial: "+248" },
  { code: "sl", name: "Sierra Leone", dial: "+232" },
  { code: "sg", name: "Singapore", dial: "+65" },
  { code: "sk", name: "Slovensko", dial: "+421" },
  { code: "si", name: "Slovenija", dial: "+386" },
  { code: "sb", name: "Solomon Islands", dial: "+677" },
  { code: "so", name: "Soomaaliya", dial: "+252" },
  { code: "za", name: "South Africa", dial: "+27" },
  { code: "ss", name: "South Sudan", dial: "+211" },
  { code: "es", name: "España", dial: "+34" },
  { code: "lk", name: "ශ්‍රී ලංකාව", dial: "+94" },
  { code: "sd", name: "السودان", dial: "+249" },
  { code: "sr", name: "Suriname", dial: "+597" },
  { code: "se", name: "Sverige", dial: "+46" },
  { code: "ch", name: "Schweiz", dial: "+41" },
  { code: "sy", name: "سوريا", dial: "+963" },
  { code: "tw", name: "臺灣", dial: "+886" },
  { code: "tj", name: "Тоҷикистон", dial: "+992" },
  { code: "tz", name: "Tanzania", dial: "+255" },
  { code: "th", name: "ประเทศไทย", dial: "+66" },
  { code: "tl", name: "Timor-Leste", dial: "+670" },
  { code: "tg", name: "Togo", dial: "+228" },
  { code: "to", name: "Tonga", dial: "+676" },
  { code: "tt", name: "Trinidad and Tobago", dial: "+1-868" },
  { code: "tn", name: "تونس", dial: "+216" },
  { code: "tr", name: "Türkiye", dial: "+90" },
  { code: "tm", name: "Türkmenistan", dial: "+993" },
  { code: "tv", name: "Tuvalu", dial: "+688" },
  { code: "ug", name: "Uganda", dial: "+256" },
  { code: "ua", name: "Україна", dial: "+380" },
  { code: "ae", name: "الإمارات", dial: "+971" },
  { code: "gb", name: "United Kingdom", dial: "+44" },
  { code: "us", name: "United States", dial: "+1" },
  { code: "uy", name: "Uruguay", dial: "+598" },
  { code: "uz", name: "Oʻzbekiston", dial: "+998" },
  { code: "vu", name: "Vanuatu", dial: "+678" },
  { code: "va", name: "Vaticano", dial: "+379" },
  { code: "ve", name: "Venezuela", dial: "+58" },
  { code: "vn", name: "Việt Nam", dial: "+84" },
  { code: "ye", name: "اليمن", dial: "+967" },
  { code: "zm", name: "Zambia", dial: "+260" },
  { code: "zw", name: "Zimbabwe", dial: "+263" },
];

/** Find country by code */
export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}
