/**
 * Single source of truth for all available fonts.
 * Used by: admin font picker, guest portal theme, preview bridge.
 *
 * 200 fonts total — focused on heading + body text suitability.
 * Sans-serif: 105 | Serif: 78 | Display (heading-safe): 9 | Mono: 7 | System: 1
 */

export interface FontDef {
  key: string;
  label: string;
  google: string | null; // Google Fonts URL param (null = system/unavailable)
  serif: boolean;
}

const sans = false;
const serif = true;

export const FONT_CATALOG: FontDef[] = [
  // ── Sans-serif (105) ──
  { key: "abel", label: "Abel", google: "Abel", serif: sans },
  { key: "albert_sans", label: "Albert Sans", google: "Albert+Sans", serif: sans },
  { key: "anek_latin", label: "Anek Latin", google: "Anek+Latin", serif: sans },
  { key: "archivo", label: "Archivo", google: "Archivo", serif: sans },
  { key: "arimo", label: "Arimo", google: "Arimo", serif: sans },
  { key: "asap", label: "Asap", google: "Asap", serif: sans },
  { key: "assistant_font", label: "Assistant", google: "Assistant", serif: sans },
  { key: "atkinson", label: "Atkinson Hyperlegible", google: "Atkinson+Hyperlegible", serif: sans },
  { key: "barlow", label: "Barlow", google: "Barlow", serif: sans },
  { key: "be_vietnam_pro", label: "Be Vietnam Pro", google: "Be+Vietnam+Pro", serif: sans },
  { key: "bricolage", label: "Bricolage Grotesque", google: "Bricolage+Grotesque", serif: sans },
  { key: "cabin", label: "Cabin", google: "Cabin", serif: sans },
  { key: "cantarell", label: "Cantarell", google: "Cantarell", serif: sans },
  { key: "catamaran", label: "Catamaran", google: "Catamaran", serif: sans },
  { key: "chakra_petch", label: "Chakra Petch", google: "Chakra+Petch", serif: sans },
  { key: "chivo", label: "Chivo", google: "Chivo", serif: sans },
  { key: "commissioner", label: "Commissioner", google: "Commissioner", serif: sans },
  { key: "darker_grotesque", label: "Darker Grotesque", google: "Darker+Grotesque", serif: sans },
  { key: "didact_gothic", label: "Didact Gothic", google: "Didact+Gothic", serif: sans },
  { key: "dm_sans", label: "DM Sans", google: "DM+Sans", serif: sans },
  { key: "dosis", label: "Dosis", google: "Dosis", serif: sans },
  { key: "encode_sans", label: "Encode Sans", google: "Encode+Sans", serif: sans },
  { key: "epilogue", label: "Epilogue", google: "Epilogue", serif: sans },
  { key: "exo_2", label: "Exo 2", google: "Exo+2", serif: sans },
  { key: "figtree", label: "Figtree", google: "Figtree", serif: sans },
  { key: "fira_sans", label: "Fira Sans", google: "Fira+Sans", serif: sans },
  { key: "geologica", label: "Geologica", google: "Geologica", serif: sans },
  { key: "golos_text", label: "Golos Text", google: "Golos+Text", serif: sans },
  { key: "gothic_a1", label: "Gothic A1", google: "Gothic+A1", serif: sans },
  { key: "gudea", label: "Gudea", google: "Gudea", serif: sans },
  { key: "hanken_grotesk", label: "Hanken Grotesk", google: "Hanken+Grotesk", serif: sans },
  { key: "heebo", label: "Heebo", google: "Heebo", serif: sans },
  { key: "hind", label: "Hind", google: "Hind", serif: sans },
  { key: "ibm_plex_sans", label: "IBM Plex Sans", google: "IBM+Plex+Sans", serif: sans },
  { key: "instrument_sans", label: "Instrument Sans", google: "Instrument+Sans", serif: sans },
  { key: "inter", label: "Inter", google: "Inter", serif: sans },
  { key: "josefin_sans", label: "Josefin Sans", google: "Josefin+Sans", serif: sans },
  { key: "jost", label: "Jost", google: "Jost", serif: sans },
  { key: "k2d", label: "K2D", google: "K2D", serif: sans },
  { key: "kanit", label: "Kanit", google: "Kanit", serif: sans },
  { key: "karla", label: "Karla", google: "Karla", serif: sans },
  { key: "kumbh_sans", label: "Kumbh Sans", google: "Kumbh+Sans", serif: sans },
  { key: "lato", label: "Lato", google: "Lato", serif: sans },
  { key: "lexend", label: "Lexend", google: "Lexend", serif: sans },
  { key: "libre_franklin", label: "Libre Franklin", google: "Libre+Franklin", serif: sans },
  { key: "link_sans", label: "Link Sans", google: "Ysabeau+SC", serif: sans },
  { key: "mada", label: "Mada", google: "Mada", serif: sans },
  { key: "manrope", label: "Manrope", google: "Manrope", serif: sans },
  { key: "maven_pro", label: "Maven Pro", google: "Maven+Pro", serif: sans },
  { key: "montserrat", label: "Montserrat", google: "Montserrat", serif: sans },
  { key: "mukta", label: "Mukta", google: "Mukta", serif: sans },
  { key: "mulish", label: "Mulish", google: "Mulish", serif: sans },
  { key: "nanum_gothic", label: "Nanum Gothic", google: "Nanum+Gothic", serif: sans },
  { key: "niramit", label: "Niramit", google: "Niramit", serif: sans },
  { key: "noto_sans", label: "Noto Sans", google: "Noto+Sans", serif: sans },
  { key: "nunito", label: "Nunito", google: "Nunito", serif: sans },
  { key: "nunito_sans", label: "Nunito Sans", google: "Nunito+Sans", serif: sans },
  { key: "onest", label: "Onest", google: "Onest", serif: sans },
  { key: "open_sans", label: "Open Sans", google: "Open+Sans", serif: sans },
  { key: "outfit", label: "Outfit", google: "Outfit", serif: sans },
  { key: "overpass", label: "Overpass", google: "Overpass", serif: sans },
  { key: "oxanium", label: "Oxanium", google: "Oxanium", serif: sans },
  { key: "oxygen", label: "Oxygen", google: "Oxygen", serif: sans },
  { key: "pathway_extreme", label: "Pathway Extreme", google: "Pathway+Extreme", serif: sans },
  { key: "plus_jakarta", label: "Plus Jakarta Sans", google: "Plus+Jakarta+Sans", serif: sans },
  { key: "pontano_sans", label: "Pontano Sans", google: "Pontano+Sans", serif: sans },
  { key: "poppins", label: "Poppins", google: "Poppins", serif: sans },
  { key: "prompt", label: "Prompt", google: "Prompt", serif: sans },
  { key: "pt_sans", label: "PT Sans", google: "PT+Sans", serif: sans },
  { key: "public_sans", label: "Public Sans", google: "Public+Sans", serif: sans },
  { key: "questrial", label: "Questrial", google: "Questrial", serif: sans },
  { key: "quicksand", label: "Quicksand", google: "Quicksand", serif: sans },
  { key: "radio_canada", label: "Radio Canada", google: "Radio+Canada", serif: sans },
  { key: "raleway", label: "Raleway", google: "Raleway", serif: sans },
  { key: "readex_pro", label: "Readex Pro", google: "Readex+Pro", serif: sans },
  { key: "red_hat_display", label: "Red Hat Display", google: "Red+Hat+Display", serif: sans },
  { key: "red_hat_text", label: "Red Hat Text", google: "Red+Hat+Text", serif: sans },
  { key: "rethink_sans", label: "Rethink Sans", google: "Rethink+Sans", serif: sans },
  { key: "roboto", label: "Roboto", google: "Roboto", serif: sans },
  { key: "roboto_condensed", label: "Roboto Condensed", google: "Roboto+Condensed", serif: sans },
  { key: "rubik", label: "Rubik", google: "Rubik", serif: sans },
  { key: "sarabun", label: "Sarabun", google: "Sarabun", serif: sans },
  { key: "schibsted_grotesk", label: "Schibsted Grotesk", google: "Schibsted+Grotesk", serif: sans },
  { key: "sen", label: "Sen", google: "Sen", serif: sans },
  { key: "signika", label: "Signika", google: "Signika", serif: sans },
  { key: "sofia_sans", label: "Sofia Sans", google: "Sofia+Sans", serif: sans },
  { key: "sora", label: "Sora", google: "Sora", serif: sans },
  { key: "source_sans", label: "Source Sans 3", google: "Source+Sans+3", serif: sans },
  { key: "space_grotesk", label: "Space Grotesk", google: "Space+Grotesk", serif: sans },
  { key: "syne", label: "Syne", google: "Syne", serif: sans },
  { key: "teko", label: "Teko", google: "Teko", serif: sans },
  { key: "tenor_sans", label: "Tenor Sans", google: "Tenor+Sans", serif: sans },
  { key: "titillium", label: "Titillium Web", google: "Titillium+Web", serif: sans },
  { key: "tomorrow", label: "Tomorrow", google: "Tomorrow", serif: sans },
  { key: "ubuntu", label: "Ubuntu", google: "Ubuntu", serif: sans },
  { key: "urbanist", label: "Urbanist", google: "Urbanist", serif: sans },
  { key: "varela_round", label: "Varela Round", google: "Varela+Round", serif: sans },
  { key: "wix_madefor", label: "Wix Madefor Text", google: "Wix+Madefor+Text", serif: sans },
  { key: "work_sans", label: "Work Sans", google: "Work+Sans", serif: sans },
  { key: "yantramanav", label: "Yantramanav", google: "Yantramanav", serif: sans },
  { key: "zen_kaku_gothic", label: "Zen Kaku Gothic New", google: "Zen+Kaku+Gothic+New", serif: sans },
  { key: "teachers", label: "Teachers", google: "Teachers", serif: sans },

  // ── Serif (83) ──
  { key: "adamina", label: "Adamina", google: "Adamina", serif },
  { key: "aleo", label: "Aleo", google: "Aleo", serif },
  { key: "alegreya", label: "Alegreya", google: "Alegreya", serif },
  { key: "alike", label: "Alike", google: "Alike", serif },
  { key: "amiri", label: "Amiri", google: "Amiri", serif },
  { key: "arvo", label: "Arvo", google: "Arvo", serif },
  { key: "biorhyme", label: "BioRhyme", google: "BioRhyme", serif },
  { key: "bitter", label: "Bitter", google: "Bitter", serif },
  { key: "bodoni_moda", label: "Bodoni Moda", google: "Bodoni+Moda", serif },
  { key: "bree_serif", label: "Bree Serif", google: "Bree+Serif", serif },
  { key: "brygada_1918", label: "Brygada 1918", google: "Brygada+1918", serif },
  { key: "caladea", label: "Caladea", google: "Caladea", serif },
  { key: "cardo", label: "Cardo", google: "Cardo", serif },
  { key: "castoro", label: "Castoro", google: "Castoro", serif },
  { key: "caudex", label: "Caudex", google: "Caudex", serif },
  { key: "corben", label: "Corben", google: "Corben", serif },
  { key: "cormorant", label: "Cormorant", google: "Cormorant", serif },
  { key: "cormorant_garamond", label: "Cormorant Garamond", google: "Cormorant+Garamond", serif },
  { key: "crete_round", label: "Crete Round", google: "Crete+Round", serif },
  { key: "crimson_pro", label: "Crimson Pro", google: "Crimson+Pro", serif },
  { key: "crimson_text", label: "Crimson Text", google: "Crimson+Text", serif },
  { key: "david_libre", label: "David Libre", google: "David+Libre", serif },
  { key: "dm_serif_display", label: "DM Serif Display", google: "DM+Serif+Display", serif },
  { key: "dm_serif_text", label: "DM Serif Text", google: "DM+Serif+Text", serif },
  { key: "domine", label: "Domine", google: "Domine", serif },
  { key: "eb_garamond", label: "EB Garamond", google: "EB+Garamond", serif },
  { key: "eczar", label: "Eczar", google: "Eczar", serif },
  { key: "esteban", label: "Esteban", google: "Esteban", serif },
  { key: "faustina", label: "Faustina", google: "Faustina", serif },
  { key: "fenix", label: "Fenix", google: "Fenix", serif },
  { key: "frank_ruhl_libre", label: "Frank Ruhl Libre", google: "Frank+Ruhl+Libre", serif },
  { key: "fraunces", label: "Fraunces", google: "Fraunces", serif },
  { key: "gelasio", label: "Gelasio", google: "Gelasio", serif },
  { key: "gentium_book", label: "Gentium Book Plus", google: "Gentium+Book+Plus", serif },
  { key: "gupter", label: "Gupter", google: "Gupter", serif },
  { key: "hahmlet", label: "Hahmlet", google: "Hahmlet", serif },
  { key: "headland_one", label: "Headland One", google: "Headland+One", serif },
  { key: "ibm_plex_serif", label: "IBM Plex Serif", google: "IBM+Plex+Serif", serif },
  { key: "inknut_antiqua", label: "Inknut Antiqua", google: "Inknut+Antiqua", serif },
  { key: "josefin_slab", label: "Josefin Slab", google: "Josefin+Slab", serif },
  { key: "kameron", label: "Kameron", google: "Kameron", serif },
  { key: "kurale", label: "Kurale", google: "Kurale", serif },
  { key: "laila", label: "Laila", google: "Laila", serif },
  { key: "libre_baskerville", label: "Libre Baskerville", google: "Libre+Baskerville", serif },
  { key: "libre_caslon", label: "Libre Caslon Text", google: "Libre+Caslon+Text", serif },
  { key: "literata", label: "Literata", google: "Literata", serif },
  { key: "lora", label: "Lora", google: "Lora", serif },
  { key: "lusitana", label: "Lusitana", google: "Lusitana", serif },
  { key: "martel", label: "Martel", google: "Martel", serif },
  { key: "mate", label: "Mate", google: "Mate", serif },
  { key: "merriweather", label: "Merriweather", google: "Merriweather", serif },
  { key: "neuton", label: "Neuton", google: "Neuton", serif },
  { key: "newsreader", label: "Newsreader", google: "Newsreader", serif },
  { key: "noticia_text", label: "Noticia Text", google: "Noticia+Text", serif },
  { key: "noto_serif", label: "Noto Serif", google: "Noto+Serif", serif },
  { key: "noto_serif_display", label: "Noto Serif Display", google: "Noto+Serif+Display", serif },
  { key: "old_standard", label: "Old Standard TT", google: "Old+Standard+TT", serif },
  { key: "petrona", label: "Petrona", google: "Petrona", serif },
  { key: "philosopher", label: "Philosopher", google: "Philosopher", serif },
  { key: "piazzolla", label: "Piazzolla", google: "Piazzolla", serif },
  { key: "playfair", label: "Playfair Display", google: "Playfair+Display", serif },
  { key: "pt_serif", label: "PT Serif", google: "PT+Serif", serif },
  { key: "quando", label: "Quando", google: "Quando", serif },
  { key: "roboto_slab", label: "Roboto Slab", google: "Roboto+Slab", serif },
  { key: "rokkitt", label: "Rokkitt", google: "Rokkitt", serif },
  { key: "sorts_mill_goudy", label: "Sorts Mill Goudy", google: "Sorts+Mill+Goudy", serif },
  { key: "source_serif", label: "Source Serif 4", google: "Source+Serif+4", serif },
  { key: "spectral", label: "Spectral", google: "Spectral", serif },
  { key: "suez_one", label: "Suez One", google: "Suez+One", serif },
  { key: "taviraj", label: "Taviraj", google: "Taviraj", serif },
  { key: "tinos", label: "Tinos", google: "Tinos", serif },
  { key: "trirong", label: "Trirong", google: "Trirong", serif },
  { key: "unna", label: "Unna", google: "Unna", serif },
  { key: "vesper_libre", label: "Vesper Libre", google: "Vesper+Libre", serif },
  { key: "vollkorn", label: "Vollkorn", google: "Vollkorn", serif },
  { key: "young_serif", label: "Young Serif", google: "Young+Serif", serif },
  { key: "gabriela", label: "Gabriela", google: "Gabriela", serif },
  { key: "gelasio", label: "Gelasio", google: "Gelasio", serif },
  { key: "pridi", label: "Pridi", google: "Pridi", serif },
  { key: "sedan", label: "Sedan", google: "Sedan", serif },
  { key: "zilla_slab", label: "Zilla Slab", google: "Zilla+Slab", serif },

  // ── Display / heading-safe (9) ──
  { key: "abril_fatface", label: "Abril Fatface", google: "Abril+Fatface", serif: sans },
  { key: "alfaslab_one", label: "Alfa Slab One", google: "Alfa+Slab+One", serif: sans },
  { key: "anton", label: "Anton", google: "Anton", serif: sans },
  { key: "bebas_neue", label: "Bebas Neue", google: "Bebas+Neue", serif: sans },
  { key: "comfortaa", label: "Comfortaa", google: "Comfortaa", serif: sans },
  { key: "fredoka", label: "Fredoka", google: "Fredoka", serif: sans },
  { key: "lilita_one", label: "Lilita One", google: "Lilita+One", serif: sans },
  { key: "oswald", label: "Oswald", google: "Oswald", serif: sans },
  { key: "righteous", label: "Righteous", google: "Righteous", serif: sans },

  // ── Mono (7) ──
  { key: "fira_code", label: "Fira Code", google: "Fira+Code", serif: sans },
  { key: "ibm_plex_mono", label: "IBM Plex Mono", google: "IBM+Plex+Mono", serif: sans },
  { key: "jetbrains_mono", label: "JetBrains Mono", google: "JetBrains+Mono", serif: sans },
  { key: "roboto_mono", label: "Roboto Mono", google: "Roboto+Mono", serif: sans },
  { key: "source_code_pro", label: "Source Code Pro", google: "Source+Code+Pro", serif: sans },
  { key: "space_mono", label: "Space Mono", google: "Space+Mono", serif: sans },
  { key: "ubuntu_mono", label: "Ubuntu Mono", google: "Ubuntu+Mono", serif: sans },

  // ── System ──
  { key: "avenir", label: "Avenir", google: null, serif: sans },
];

/** Generate a FontKey union type from the catalog */
export type CatalogFontKey = (typeof FONT_CATALOG)[number]["key"];

/** Build a Google Fonts URL for a batch of FontDefs */
export function batchFontsUrl(fonts: FontDef[]): string | null {
  const googleFonts = fonts.filter((f) => f.google);
  if (googleFonts.length === 0) return null;

  const params = googleFonts
    .map((f) => `family=${f.google}:wght@400;600`)
    .join("&");

  return `https://fonts.googleapis.com/css2?${params}&display=swap`;
}
