-- AlterEnum
ALTER TYPE "OrderEventType" ADD VALUE 'CHANNEL_ORDER_RECEIVED';
ALTER TYPE "OrderEventType" ADD VALUE 'CHANNEL_ORDER_UPDATED';
ALTER TYPE "OrderEventType" ADD VALUE 'CHANNEL_ORDER_CANCELLED';
ALTER TYPE "OrderEventType" ADD VALUE 'CHANNEL_SYNC_ERROR';
